# Generated by Django 6.0 on 2026-01-01 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AmfiMonthlyData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.CharField(help_text='Reporting month, e.g. November 2025', max_length=20)),
                ('scheme_category', models.CharField(help_text='Scheme category like Large Cap, Mid Cap, Small Cap', max_length=200)),
                ('net_inflow', models.FloatField(blank=True, help_text='Net inflow/outflow value for the month', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'AMFI Monthly Data',
                'verbose_name_plural': 'AMFI Monthly Data',
                'unique_together': {('month', 'scheme_category')},
            },
        ),
    ]
