# Generated by Django 6.0 on 2026-01-01 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market_data', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='amfimonthlydata',
            name='net_inflow',
            field=models.FloatField(blank=True, help_text='Net inflow/outflow value for the month (INR Crores)', null=True),
        ),
        migrations.AddIndex(
            model_name='amfimonthlydata',
            index=models.Index(fields=['month'], name='market_data_month_38c2fd_idx'),
        ),
        migrations.AddIndex(
            model_name='amfimonthlydata',
            index=models.Index(fields=['scheme_category'], name='market_data_scheme__3e4d6e_idx'),
        ),
    ]
